config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'events#index'
  resources :users  
  resources :events do
    resources :attendances
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # after_create :report_admin_send

  belongs_to :guest, class_name: "User"
  belongs_to :event

  def report_admin_send
    AdminMailer.admin_report_email(self.event.admin).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :guests, foreign_key: 'event_id', class_name: "User", through: :attendances


  validates :start_date,
    presence: true

  validate :start_date_is_in_future?

  validates :duration,
    presence: true,
    numericality: { greater_than_or_equal_to: 0 }
  
  validate :duration_is_a_multiple_of_5?

  validates :title,
    presence: true,
    length: { in: 5..140 }

  validates :description,
    presence: true,
    length: { in: 20..1000 }

  validates :price,
    presence: true,
    numericality: true,
    inclusion: { in: 1..1000, message: "Value should be between 1 and 1000"}

  validates :location,
    presence: true

  def start_date_is_in_future?
    errors.add(:start_date, "must be in the future") unless
       self.start_date > Time.now
  end

  def duration_is_a_multiple_of_5?
    errors.add(:duration, "must be a multiple of 5") unless
    self.duration % 5 == 0
  end 

  def end_date
    return self.start_date + self.duration*60
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # after_create :welcome_send

  has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'guest_id', class_name: 'Attendance'

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @event_id = params[:event_id]
    @event = Event.find(@event_id)
  
    @attendances = Attendance.where(event: @event)
  
  end

  def new
    @event_id = params[:event_id]
    @event = Event.find(@event_id) 
  end

  def create
    # Before the rescue, at the beginning of the method
    @stripe_amount = 500

    @event_id = params[:event_id]
    @event = Event.find(@event_id) 
    user = current_user

    begin
      
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to @attendance
    end

    @attendance = Attendance.new(event: @event, guest: user, stripe_customer_id: customer.id) 


    if @attendance.save 
      flash[:Notice] = "You enrolled succesfully"
      redirect_to @event
    else
      flash.now[:notice] = @attendance.errors.full_messages
      render :new
    end


  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :authenticate_user!

  def index
    @events = Event.all
    @events = @events.sort_by {|event| event.start_date}

  end

  def show
    @event_id = params[:id]
    @events = Event.all

    @event = @events.find(@event_id)
    @guests_event = Attendance.where(event: @event)

  end

  def new
  end

  def create
    user = current_user

    @event = Event.new(title: params[:event_title], start_date: params[:event_start_date], duration:params[:event_duration],
                       description: params[:event_description], price: params[:event_price], location: params[:event_location],
                       admin: user) 

    if @event.save 
      flash[:Notice] = "Event successfully created"
      redirect_to @event
    else
      flash.now[:notice] = @event.errors.full_messages
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])

    unless is_user_admin?
      flash[:danger] = "Action impossible"
      redirect_to @event
    end
  end

  def update
    @event = Event.find(params[:id])

    unless is_user_admin?
      flash[:danger] = "Action impossible"
      redirect_to @event
    end

    if @event.update(title: params[:event_title], start_date: params[:event_start_date], duration:params[:event_duration],
                     description: params[:event_description], price: params[:event_price], location: params[:event_location])
      
      flash[:Notice] = "Event modified successfully"
      redirect_to @event
    else
      flash.now[:notice] = @event.errors.full_messages
      render :edit
    end

  end

  def destroy
    @event = Event.find(params[:id])

    unless is_user_admin?
      flash[:danger] = "Action impossible"
      redirect_to @event
    end
    
    @event.destroy

    if @event.destroy
      flash[:Notice] = "Event deleted"
      redirect_to :root
    else
      flash.now[:notice] = "did not work"
      render @event
    end
  
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user_id = params[:id]
    @users = User.all

    @user = @users.find(@user_id)
    p @events_admin = Event.where(admin: @user)

    unless current_user == @user
      flash[:danger] = "Action impossible"
      redirect_to :root
    end
  end
  
  def edit
    @user = User.find(params[:id])

    unless current_user == @user
      flash[:danger] = "Action impossible"
      redirect_to :root
    end
  end

  def update
    @user = User.find(params[:id])

    unless current_user == @user
      flash[:danger] = "Action impossible"
      redirect_to @user
    end

    if @user.update(first_name: params[:user_first_name], last_name: params[:user_last_name], description: params[:user_description])
      flash[:Notice] = "Information modified successfully"
      redirect_to @user
    else
      flash.now[:notice] = @user.errors.full_messages
      render :edit
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def is_user_attending?
    event = Event.find(params[:id])
    user = current_user

    Attendance.where(event: event, guest: user).count != 0 ? true : false
  end



end

app/helpers/events_helper.rb
module EventsHelper
  def is_user_admin?
    event = Event.find(params[:id])
    user = current_user

    event.admin == user ? true : false
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

        <div class = "mx-3">
            

            <div>
                <% flash.each do |msg| %>
                <div class="alert alert-success">
                    <%= msg.join(": ").html_safe %>
                        
                </div>
                <% end %>
                
                <div class="carte">
                    <div>
                        <h1 class="mb-4 title"><%=@event.title %></h1>
                        <div>
                            <h4>Number of guests</span>: <%=@attendances.count %> <br/></h4>
                        </div>
                        <div>
                            <h4 class="mb-4">Guest list</h4>
                            <% @attendances.map do |attendance| %>
                            <p><%= attendance.guest.first_name %> <%= attendance.guest.last_name %>  <br/></p>

                            <% end %>
                        </div>
                    </div>
                    <p>
                        <%= link_to "Edit event", edit_event_path(@event.id), class: "btn btn-success btn-lg mt-3 mr-2"%>
                        <%= link_to "Delete event", event_path(@event.id), method: :delete, class: "btn btn-danger btn-lg mt-3 ml-2"%>
                    </p>
                </div>
            </div>
        </div>

  </body>

</html>

app/views/attendances/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

    <div class = "mx-3">
        
        <div>
            <% flash.each do |msg| %>
            <div class="alert alert-danger">
                <%= msg.join(": ").html_safe %>
                    
            </div>
            <% end %>
            
            <div class="carte">
                <div>
                    <h1 class="mb-4 title"><%= @event.title %></h1>
                <div>

                              <%= form_tag url_for(action: 'create'), method: "post" do %>
                              <article>
                                <% if flash[:error].present? %>
                                  <div id="error_explanation">
                                    <p><%= flash[:error] %></p>
                                  </div>
                                <% end %>
                                <label class="amount mb-4">
                                  <span>Amount to pay: <%= @event.price%>$</span>
                                </label>
                              </article>
                              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                  data-description="Achat d'un produit"
                                  data-amount= "<%= @event.price * 100  %>""
                                  data-locale="auto">
                              </script>
                              <% end %>



            </div>

        </div>
    </div>

  </body>

</html>

app/views/events/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

    <div class = "mx-3">
        
        <div>
            <% flash.each do |msg| %>
            <div class="alert alert-danger">
                <%= msg.join(": ").html_safe %>
                    
            </div>
            <% end %>
            
            <div class="carte">
                <div>
                    <h1 class="mb-4 title">Edit event</h1>
                <div>

                <%= form_tag url_for(action: 'update'), method: "patch" do %>

                    <h4><%= label_tag 'Title' %></h4>
                    <%= text_field_tag 'event_title', @event.title, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Start date' %></h4>
                    <%= text_field_tag 'event_start_date', @event.start_date, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Duration in minute' %></h4>
                    <%= text_field_tag 'event_duration', @event.duration, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Description' %></h4>
                    <%= text_field_tag 'event_description', @event.description, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Price' %></h4>
                    <%= text_field_tag 'event_price', @event.price, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Location' %></h4>
                    <%= text_field_tag 'event_location', @event.location, class: "form-control" %>
                    <br /> <br />

                    <%= submit_tag("Apply modification", :class=>"btn btn-info btn-lg btn-block") %>

                <% end %>

                <div>
                    <h3 class="mt-5 text-white">Change of plan?</h3>
                    <%= link_to "Delete event", event_path(@event.id), method: :delete, class: "btn btn-danger btn-block btn-lg mt-3 ml-2"%>
                <div>
            </div>

        </div>
    </div>

  </body>

</html>

app/views/events/index.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                body {
                font-family: Arial, Helvetica, sans-serif;
                }

                .flip-card {
                background-color: transparent;
                width: 300px;
                height: 300px;
                perspective: 1000px;
                }

                .flip-card-inner {
                position: relative;
                width: 100%;
                height: 100%;
                text-align: center;
                transition: transform 0.6s;
                transform-style: preserve-3d;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

                .flip-card:hover .flip-card-inner {
                transform: rotateY(180deg);
                }

                .flip-card-front, .flip-card-back {
                position: absolute;
                width: 100%;
                height: 100%;
                -webkit-backface-visibility: hidden;
                backface-visibility: hidden;
                }

                .flip-card-front {
                background-color: #bbb;
                color: black;
                }

                .flip-card-back {
                background-color: #2980b9;
                color: white;
                transform: rotateY(180deg);
                }
            </style>
        </head>

    <body>

        <div class = "mx-3">

            <% flash.each do |msg| %>
            <div class="alert alert-success">
                <%= msg.join(": ").html_safe %>
                
            </div>
            <% end %>

        <!-- Reste de la page -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col px-3">
                        <% if current_user.first_name != nil %>
                        <div class="jumbotron py-3 my-3 bg-dark text-white">
                            <h1 class="text-warning">Hello <span class="text-white"><%= current_user.first_name %></span>, and Welcome on <span class="font-weight-bold text-white">Eventbrite</span></h1>
                            <p class="mt-3">Here is the list of events available<br/>
                        </div>

                        <% else %>
                        <div class="jumbotron py-3 my-3 bg-dark text-white">
                            <h1 class="text-warning">Hello, and Welcome on <span class="font-weight-bold text-white">Eventbrite</span></h1>
                            <p class="mt-3">Here is the list of events available<br/>
                        </div>
                        <% end %>

                    </div>  
                </div>

                <ul class="d-flex list-unstyled">
                    <li><%= link_to "Create event", new_event_path, class: "btn btn-info btn-lg text-light mt-3 mr-3" %></li>
                </ul>

                <div class="row">
                <% @events.map do |event| %>
                    <div class="col-12 col-sm-4 my-3 flip-card border-success">
                        <div class="flip-card-inner">
                            <div class="flip-card-front bg-light d-flex flex-column">
                                <div class="card-header text-center pb-1 text-white bg-dark">
                                    <h2><%=event.title%></h2>
                                </div>
                                <div class="my-auto">
                                    <h2 class="card-title text-warning py-2"><%=event.price%>$</h2>
                                    <h4 class="card-text text-info"><%=event.description%></h4>
                                </div>
                            </div>

                            <div class="flip-card-back d-flex flex-column bg-white">
                                <div class="card-header text-center pb-1 text-wh bg-dark">
                                    <h2><%=event.title%></h2>
                                </div>
                                <div class="my-auto">
                                    <p><%= link_to "See more", event_path(event.id), class: "btn btn-success btn-lg"%></p>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
                </div>





            </div>
        </div>


    </body>


</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

    <div class = "mx-3">
        
        <div>
            <% flash.each do |msg| %>
            <div class="alert alert-danger">
                <%= msg.join(": ").html_safe %>
                    
            </div>
            <% end %>
            
            <div class="carte">
                <div>
                    <h1 class="mb-4 title">New event</h1>
                <div>

                <%= form_tag url_for(action: 'create'), method: "post" do %>

                    <h4><%= label_tag 'Title' %></h4>
                    <%= text_field_tag 'event_title', "", class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Start date' %></h4>
                    <%= text_field_tag 'event_start_date', "", class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Duration in minute' %></h4>
                    <%= text_field_tag 'event_duration', "", class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Description' %></h4>
                    <%= text_field_tag 'event_description', "", class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Price' %></h4>
                    <%= text_field_tag 'event_price', "", class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Location' %></h4>
                    <%= text_field_tag 'event_location', "", class: "form-control" %>
                    <br /> <br />

                    <%= submit_tag("Create the event", :class=>"btn btn-info") %>

                <% end %>
            </div>

        </div>
    </div>

  </body>

</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

        <div class = "mx-3">
            

            <div>
                <% flash.each do |msg| %>
                <div class="alert alert-success">
                    <%= msg.join(": ").html_safe %>
                        
                </div>
                <% end %>
                
                <div class="carte">
                    <div>
                        <h1 class="mb-4 title"><%=@event.title %></h1>
                        <p><span class="font-weight-bold">Description</span>: <%=@event.description %></p>
                        <p><span class="font-weight-bold">Number of attendees</span>: <%=@guests_event.count %></p>
                        <p><span class="font-weight-bold">Organized by</span>: <%=@event.admin.email %></p>
                        <p><span class="font-weight-bold">Start date</span>: <%=@event.start_date %></p>
                        <p><span class="font-weight-bold">End date</span>: <%=@event.end_date %></p>

                        <p><span class="font-weight-bold">Location</span> <%= @event.location %></p>
                        <p><span class="font-weight-bold">Price</span> <%= @event.price %></p>

                        <p>
                            <span class="font-weight-bold"> Event created on</span>: <%=@event.created_at%> <br />
                            <span class="font-weight-bold"> Event updated on</span>: <%=@event.updated_at%> 
                        </p>

                        <% if is_user_admin? %>
                            <%= link_to "Event profile", event_attendances_path(@event.id), class: "btn btn-primary btn-lg text-light mt-3 mr-3" %>
                        
                        <% elsif is_user_attending? %>
                            <h4 class="mt-4 text-info">You applied to this event</h4>
                        <% else %>
                            <%= link_to "Join", new_event_attendance_path(@event.id), class: "btn btn-primary btn-lg text-light mt-3 mr-3" %>
                        <% end %>

                    </div>
                </div>
            </div>
        </div>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    body {
      background-color: #dfe5e8;
      margin-top: 60px;
      margin-left: 30px;
    }

  </style>    

  </head>

  <body>
    <%= yield %>

    <!-- Navbar session on -->
    <% if current_user != nil %>
    <div class="bg-dark fixed-top">
      <div class="container-fluid">
        <div class="row">
          <nav class="col navbar navbar-expand-lg navbar-dark">
            <h4 class="mr-4 mt-2 py-1"><%= link_to "Eventbrite", root_path, class: "text-light font-weight-bold ml-3" %></h4>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarContent" class="collapse navbar-collapse justify-content-between">
              <ul class="navbar-nav mt-1">
                <li class="nav-item active mr-4">
                  <%= link_to "Home", root_path, class:"text-light" %>
                </li>
                <li class="nav-item active mr-4">
                  <%= link_to "Create event", new_event_path, class:"text-light" %>
                </li>
              </ul>
              <div class="dropdown navbar-nav mt-2 mr-3 d-flex justify-content-end">
                <a class="btn btn-light text-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  My profile
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%# <%= link_to "Mon profil", user_path(user_session.id), class:"dropdown-item" %>
                  <%= link_to "My profile", user_path(current_user.id), class:"dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
    <!-- Navbar session on -->

    <!-- Navbar session off -->
    <% else %>
    <div class="bg-dark fixed-top">
      <div class="container-fluid">
        <div class="row">
          <nav class="col navbar navbar-expand-lg navbar-dark">
            <h4 class="mr-4 mt-2 py-1"><%= link_to "Eventbrite", root_path, class: "text-light font-weight-bold ml-3" %></h4>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarContent" class="collapse navbar-collapse justify-content-between">
            <div id="navbarContent" class="collapse navbar-collapse justify-content-between">
              <ul class="navbar-nav mt-1">
              </ul>
              <div class="dropdown navbar-nav mt-2 mr-3 d-flex justify-content-end">
                <a class="btn btn-light text-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Connection
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "Sign up", new_user_registration_path, class:"dropdown-item" %>
                  <%= link_to "Log in", new_user_session_path, class:"dropdown-item" %>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
    <% end %>
    <!-- Navbar session off -->

    

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>



 

  </body>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', async: Rails.env.production?, :cache => 'cached/all' %>

</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

    <div class = "mx-3">
        <div>
            <div class="carte">
                <div>
                    <h1 class="mb-4 title">New event</h1>
                <div>

                <%= form_tag url_for(action: 'update'), method: "patch" do %>

                    <h4><%= label_tag 'First name' %></h4>
                    <%= text_field_tag 'user_first_name', @user.first_name, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Last name' %></h4>
                    <%= text_field_tag 'user_last_name', @user.last_name, class: "form-control" %>
                    <br /> <br />

                    <h4><%= label_tag 'Bio' %></h4>
                    <%= text_field_tag 'user_description', @user.description, class: "form-control" %>
                    <br /> <br />

                    <%= submit_tag("Update my information", :class=>"btn btn-info") %>

                <% end %>
            </div>
        </div>
    </div>



  </body>

</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    .carte {
        background-color: #b0bec7;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

    <div class = "mx-3">
        <div>
            <div class="carte">
                <div>
                    <h1 class="mb-4 title">My personal information</h1>
                </div>
                <div>
                    <p><span class = "font-weight-bold">First name</span>: <%=@user.first_name%></p>
                    <p><span class = "font-weight-bold">Last name</span>: <%=@user.last_name%></p>
                    <p><span class = "font-weight-bold">Bio</span>: <%=@user.description%></p>
                    <p><span class = "font-weight-bold">Email</span>: <%=@user.email%></p>
                </div>

                <div>
                    <%= link_to "Update my information", edit_user_path(current_user.id), class: "btn btn-info mt-3"%>
                    <%= link_to "Update my password and email", edit_user_registration_path, class: "btn btn-warning mt-3"%>

                </div>

                <% if @events_admin.count !=0 %>
                <div>
                    <h4 class="mt-5">Events you organized</h4>
                    <% @events_admin.map do |event| %>
                    <ul class="list-unstyled">
                        <li>> <%= link_to event.title, event_path(event.id) %></li>
                    </ul>
                    <% end %>
                </div>
                <% end %>

            </div>
        </div>
    </div>



  </body>

</html>